import type { BbPluginApi } from "@get-bb/plugin-sdk";
import { z } from "zod";
import type { ReferenceService } from "../services/reference-service.ts";

export function registerAgentTools(bb: BbPluginApi, service: ReferenceService): void {
  // 1. Tool: references_add
  bb.agents.registerTool({
    name: "references_add",
    description:
      "Add a visual reference (image URL or local image path) to the current project's moodboard.",
    parameters: z.object({
      urlOrPath: z.string().describe("Web image URL (https://...) or local file path (e.g. docs/references/hero.png)"),
      title: z.string().optional().describe("Descriptive title for the reference"),
      tags: z.array(z.string()).optional().describe("Tags for categorization (e.g. ['ui', 'dark-mode', 'dashboard'])"),
      notes: z.string().optional().describe("Design context or notes explaining what is notable about this reference"),
      prompt: z.string().optional().describe("The exact text prompt used to generate this image (when generated by an image generation tool)"),
      pinned: z.boolean().optional().describe("Mark as an active aesthetic anchor reference"),
    }),
    async execute(params, ctx) {
      const pid = ctx.projectId || "default";
      const ref = await service.add(pid, {
        urlOrPath: params.urlOrPath,
        title: params.title,
        tags: params.tags,
        notes: params.notes,
        prompt: params.prompt,
        pinned: params.pinned,
        source: "agent",
      });

      bb.realtime.publish("references-changed", { projectId: ref.projectId });

      const promptInfo = ref.prompt ? `\nPrompt: "${ref.prompt}"` : "";

      return {
        content: [
          {
            type: "text",
            text: `Added reference "${ref.title}" [${ref.id}] to project "${ref.projectName || ref.projectId}".${promptInfo}\n\n::reference{id="${ref.id}" project="${ref.projectId}"}\n\n[🖼️ Open in References panel](#reference:${ref.projectId}/${ref.id})`,
          },
        ],
      };
    },
  });

  // 2. Tool: references_pin
  bb.agents.registerTool({
    name: "references_pin",
    description:
      "Pin or unpin a reference to mark it as the project's active aesthetic anchor.",
    parameters: z.object({
      id: z.string().describe("Reference ID to pin or unpin"),
      pinned: z.boolean().optional().describe("true to pin, false to unpin. Omit to toggle current state."),
    }),
    async execute(params, ctx) {
      const pid = ctx.projectId || "default";
      const current = await service.get(pid, params.id);
      if (!current) {
        return {
          content: [
            {
              type: "text",
              text: `Reference with ID "${params.id}" not found.`,
            },
          ],
        };
      }

      let targetPinned = !current.pinned;
      if (params.pinned !== undefined) {
        targetPinned = params.pinned;
      }

      if (current.pinned !== targetPinned) {
        await service.togglePin(pid, params.id);
        bb.realtime.publish("references-changed", { projectId: current.projectId });
      }

      return {
        content: [
          {
            type: "text",
            text: `${targetPinned ? "📌 Pinned anchor reference" : "Unpinned anchor reference"}: "${current.title}" [${current.id}]`,
          },
        ],
      };
    },
  });

  // 3. Tool: references_list
  bb.agents.registerTool({
    name: "references_list",
    description: "List visual references and moodboard items for the current project in BB IDE.",
    parameters: z.object({
      tag: z.string().optional().describe("Filter references by specific tag"),
      query: z.string().optional().describe("Search query matching title, notes, or URL"),
    }),
    async execute(params, ctx) {
      const pid = ctx.projectId || "default";
      const refs = await service.list(pid, { tag: params.tag, query: params.query });
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(refs, null, 2),
          },
        ],
      };
    },
  });
}
